version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile-database
    ports:
      - "27017:27017"
